config/routes.rb
Rails.application.routes.draw do
  resources :organizations, only: [:index]

  root 'organizations#index'

end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_and_belongs_to_many :organizations, :uniq => true
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  validates :org_number, presence: true, uniqueness: true
  has_and_belongs_to_many :keywords, :uniq => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
	respond_to :json, :xml, :html
  # GET /organizations
  # GET /organizations.json
  # GET /organizations.xml
  def index
    if params[:what].present?
      @search_query = params[:what].strip
      @organizations = OrganizationsSearch.search(@search_query)
      flash[:notice] = "No results." if @organizations.blank?
    else
      @organizations = Organization.none
    end
    respond_with @organizations
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FindCompany</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/organizations/_find_company_form.html.erb
<%= form_tag("/organizations", method: "get", enforce_utf8: false) do %>
  <%= label_tag(:what, "WHAT ARE YOU LOOKING FOR?") %><br />
  <%= text_field_tag :what, @search_query, required: true %>
  <%= submit_tag "Search", name: nil %><br />
  Enter Companies, Personal names, Industry OR FREE WORD
<% end %>

app/views/organizations/_organizations_details.html.erb
<h3>Search Results: <%= link_to 'Get JSON', organizations_path(format: :json, what: @search_query), target: :blank %>&nbsp;|
<%= link_to 'Get XML', organizations_path(format: :xml, what: @search_query), target: :blank %></h3>
<table id="organizations">
  <thead>
    <tr>
      <th>Name</th>
      <th>Org number</th>
      <th>City</th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.name %></td>
        <td><%= organization.org_number %></td>
        <td><%= organization.city %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/organizations/index.html.erb
<%= render 'find_company_form' %>
<% if @organizations.present? %>
  <%= render 'organizations_details' %>
<% else %>
  <h3 id="notice"><%= notice %></h3>
<% end %>